
extsecrets:
  enabled: false

datadog:
  datadog:
    apiKeyExistingSecret: datadog-secret
    appKeyExistingSecret: datadog-secret
    clusterName: gilad-test-cluster
    dogstatsd:
      nonLocalTraffic: true
      port: 8125
    logs:
      containerCollectAll: true
      enabled: true
    processAgent:
      enabled: true
      processCollection: true
    site: datadoghq.com
  clusterAgent:
    admissionController:
      enabled: true
      mutateUnlabelled: true
    createPodDisruptionBudget: true
    replicas: 2
  targetSystem: linux
  agents:
    enabled: true
