apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  # annotations:
  #   argocd.argoproj.io/sync-wave: "-1"
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 3
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.18
        ports:
        - containerPort: 80
