apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: canary-demo-promote
  namespace: rollout
spec:
  replicas: 3
  strategy:
    canary:
      steps:
      - setWeight: 25
      - pause: {}
      - setWeight: 50
      - pause: {}
      - setWeight: 75
      - pause: {}
  selector:
    matchLabels:
      app: demo-app
  template:
    metadata:
      labels:
        app: demo-app
    spec:
      containers:
      - name: demo-container
        image: nginx:1.18.0
        ports:
        - containerPort: 80
