apiVersion: v1
kind: Secret
metadata:
  name: datadog-secret
  namespace: datadog
type: Opaque
data:
  api-key: {{ randAlphaNum 20 | b64enc | quote }}
  app-key: {{ randAlphaNum 20 | b64enc | quote }}