apiVersion: batch/v1
kind: Job
metadata:
  name: simple-success-job
  namespace: test
  annotations:
    # argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  ttlSecondsAfterFinished: 100  # Job will be deleted 60 seconds after completion
  template:
    metadata:
      name: simple-success-job
    spec:
      restartPolicy: Never
      containers:
      - name: success-container
        image: busybox
        command: ['sh', '-c', 'sleep 5 && echo "success" && exit 0']
