apiVersion: batch/v1
kind: Job
metadata:
  name: liquibase-runner-job-20240424171318
  labels:
    job: liquibase-runner-job-20240424171318
spec:
  parallelism: 1
  completions: 1
  activeDeadlineSeconds: 1800
  ttlSecondsAfterFinished: 2628000
  selector:
    matchLabels:
      job: liquibase-runner-job-20240424171318
  template:
    metadata:
      labels:
        job: liquibase-runner-job-20240424171318
    spec:
      serviceAccountName: default
      containers:
        - name: liquibase-runner-job-20240424171318
          image: busybox:glibc
          command: ["sh", "-c", "sleep 2 && echo success new! && exit 0"]
      restartPolicy: Never
