---
apiVersion: batch/v1
kind: Job
metadata:
  name: liquibase-runner-job-202404241724529
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
  labels:
    job: liquibase-runner-job-202404241724529
spec:
  parallelism: 1
  completions: 1
  activeDeadlineSeconds: 1800
  ttlSecondsAfterFinished: 2628000
  template:
    metadata:
      labels:
        job: liquibase-runner-job-202404241724529
    spec:
      serviceAccountName: default
      containers:
        - name: liquibase-runner-job-202404241724529
          image: busybox:glibc
          command: ["sh", "-c", "sleep 30 && echo success new!!! && exit 0"]
      restartPolicy: "Never"
  backoffLimit: 3
