---
apiVersion: batch/v1
kind: Job
metadata:
  name: liquibase-runner-job-2024042417245295
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
  labels:
    job: liquibase-runner-job-2024042417245295
spec:
  parallelism: 1
  completions: 1
  activeDeadlineSeconds: 1800
  ttlSecondsAfterFinished: 2628000
  template:
    metadata:
      labels:
        job: liquibase-runner-job-2024042417245295
    spec:
      serviceAccountName: default
      containers:
        - name: liquibase-runner-job-2024042417245295
          image: busybox:glibc
          command: ["sh", "-c", "sleep 20 && echo success && exit 0"]
      restartPolicy: "Never"
  backoffLimit: 3
