apiVersion: batch/v1
kind: Job
metadata:
  generateName: simple-success-job-
  namespace: test
  annotations:
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  template:
    spec:
      containers:
      - name: success-container
        image: busybox
        command: ["sh", "-c", "sleep 5 && echo success && exit 0"]
      restartPolicy: Never
  ttlSecondsAfterFinished: 10000
