apiVersion: batch/v1
kind: Job
metadata:
  generateName: simple-success-job-
  namespace: test 
  # annotations:
  #   argocd.argoproj.io/hook: PreSync
    # argocd.argoproj.io/hook-delete-policy: HookSucceeded
  labels:
    argocd.argoproj.io/instance: my-job
spec:
  template:
    spec:
      containers:
      - name: success-container
        image: busybox
        command: ["sh", "-c", "sleep 2 && echo success new! && exit 0"]
      restartPolicy: Never
  ttlSecondsAfterFinished: 100
