---
apiVersion: batch/v1
kind: Job
metadata:
  name: liquibase-runner-job-20240424172452
  labels:
    job: liquibase-runner-job-20240424172452
spec:
  parallelism: 1
  completions: 1
  activeDeadlineSeconds: 1800
  ttlSecondsAfterFinished: 2628000
  template:
    metadata:
      labels:
        job: liquibase-runner-job-20240424172452
    spec:
      serviceAccountName: default
      containers:
        - name: liquibase-runner-job-20240424172452
          image: busybox:glibc
          command: ["sh", "-c", "sleep 2 && echo success new! && exit 0"]
      restartPolicy: "Never"
  backoffLimit: 3
